### ISSUE TITLE
ConnectionAbortedError: [WinError 10053]: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by LeonardoRick** [iterative/PyDrive2#105]
I want to authenticate on windows using this code:

```python

def setupDrive(self, attempt=1):
    try:
        gauth = GoogleAuth()
        gauth.LoadCredentialsFile('credentials.json')
        if gauth.credentials is None:
            # Authenticate if they're not there
            gauth.LocalWebserverAuth()
        elif gauth.access_token_expired:
            # Refresh them if expired
            gauth.Refresh()
        else:
            # Initialize the saved creds
            gauth.Authorize()
        # Save the current credentials to a file
        gauth.SaveCredentialsFile('credentials.json')
        return GoogleDrive(gauth)
    except RefreshError as e:
        if attempt == 1:
            Path('credentials.json').unlink(missing_ok=True)
            return self.setupDrive(attempt=2)
        else:
            raise e

setupDrive()
```

But it looks like its loosing connection during authentication.  Is there a way to know which program is closing the connection? I already disabled anti-virus and windows firewall but the following error keeps happennig:

```
C:\Users\leona\AppData\Roaming\Python\Python39\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access credentials.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=560077035476-tglchf945j6a1e5k3hf4o72t777nivk7.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code&approval_prompt=force

----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 63600)
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files\Python39\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files\Python39\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\Python39\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Program Files\Python39\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "C:\Program Files\Python39\lib\http\server.py", line 415, in handle_one_request
    method()
  File "C:\Users\leona\AppData\Roaming\Python\Python39\site-packages\oauth2client\tools.py", line 133, in do_GET
    self.wfile.write(
  File "C:\Program Files\Python39\lib\socketserver.py", line 826, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine 
----------------------------------------
Failed to find "code" in the query parameters of the redirect.
Try command-line authentication
Traceback (most recent call last):
  File "C:\Users\leona\iq\iq-package\upload.py", line 127, in <module>
    goog = G()
  File "C:\Users\leona\iq\iq-package\upload.py", line 53, in __init__
    self.drive = self.setupDrive()
  File "C:\Users\leona\iq\iq-package\upload.py", line 63, in setupDrive
    gauth.LocalWebserverAuth()
  File "C:\Users\leona\AppData\Roaming\Python\Python39\site-packages\pydrive2\auth.py", line 125, in _decorated
    code = decoratee(self, *args, **kwargs)
  File "C:\Users\leona\AppData\Roaming\Python\Python39\site-packages\pydrive2\auth.py", line 269, in LocalWebserverAuth
    raise AuthenticationError("No code found in redirect")
pydrive2.auth.AuthenticationError: No code found in redirect
```

**Comment by shcheklein** [comment]
Closing as stale
