### ISSUE TITLE
Predefined Login

### ISSUE THREAD

**Issue by KeparYTbcc** [iterative/PyDrive2#174]
Hi, i wanted to do like somes AUTO BACKUP, but it ask for oauth each time, can't i just like predefine the acc i want,
Like put the password + name in the script and avoid gettin the oauth page

**Comment by KeparYTbcc** [comment]
EX:
```
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive

gauth = GoogleAuth("Email","password")
gauth.LocalWebserverAuth()

drive = GoogleDrive(gauth)```

**Comment by KeparYTbcc** [comment]
can i compile this "Settings.yaml" in pyinstaller?

**Comment by KeparYTbcc** [comment]
```
PS F:\bot-dev\csn\PROJECT LOLI> py loli.py
Traceback (most recent call last):
  File "F:\bot-dev\csn\PROJECT LOLI\loli.py", line 18, in <module>
    gauth.LocalWebserverAuth()       
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\pydrive\auth.py", line 113, in _decorated
    self.GetFlow()
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\pydrive\auth.py", line 443, in GetFlow
    self.LoadClientConfig()
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\pydrive\auth.py", line 366, in LoadClientConfig    
    self.LoadClientConfigFile()
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\pydrive\auth.py", line 384, in LoadClientConfigFile    client_config_file = self.settings['client_config_file']
KeyError: 'client_config_file'

**Comment by Kolhax** [comment]
@shcheklein

**Comment by shcheklein** [comment]
@Kolhax 

It looks like you are using an older version of the lib, btw?

> can i compile this "Settings.yaml" in pyinstaller?

I would do it this way then: https://github.com/iterative/dvc/blob/main/dvc/fs/gdrive.py#L224 - read the code around it. Basically it's overriding the default config values in the class to avoid creating the settings.yaml file. So everything is done in Python.


> KeyError: 'client_config_file'

could you share the code that you are running please?
