### ISSUE TITLE
multithreading with PyDrive2?

### ISSUE THREAD

**Issue by mozboz** [iterative/PyDrive2#43]
I have a lot of files to download, and I want to do it in a few threads concurrently.

First should I expect that to work with PyDrive2? I'm passing around a pydrive2.drive object to all my threads.

If that's a sensible thing to do, it seems to work ok, but occasionally I get this. Can anyone shed any light on it? I haven't understood the auth mechanism well, perhaps I should be manually refreshing tokens or something before I start a large job?

Thanks for any help/pointers

```
INFO:oauth2client.client:access_token is expired. Now: 2020-06-02 23:31:17.367175, token_expiry: 2020-06-02 23:31:16
INFO:oauth2client.client:access_token is expired. Now: 2020-06-02 23:31:17.367702, token_expiry: 2020-06-02 23:31:16
INFO:oauth2client.client:Refreshing access_token
DEBUG:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271igPrqZFBdr_xIrJD3AIbbz6q_RuWzqUY%27+in+parents+and+trashed%3Dfalse&supporBAZllDrives=true&includeItemsFromAllDrives=true&maxResults=1000&alt=json
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 48, in worker
    gdb.recursive_report(job['folderId'], job['parentId'], job['localRoot'], job['remotePath'])
  File "/home/MYNAME/dev/BAZ-Google-Drive-Sync/backupfunctions.py", line 45, in recursive_report
    file_list = self.drive.ListFile({'q': "'" + folderId + "' in parents and trashed=false"}).GetList()
  File "/home/MYNAME/dev/BAZ/BAZ_env/lib/python3.5/site-packages/pydrive2/apiattr.py", line 166, in GetList
    for x in self:
  File "/home/MYNAME/dev/BAZ/BAZ_env/lib/python3.5/site-packages/pydrive2/apiattr.py", line 150, in __next__
    result = self._GetList()
  File "/home/MYNAME/dev/BAZ/BAZ_env/lib/python3.5/site-packages/pydrive2/auth.py", line 60, in _decorated
    self.auth.LocalWebserverAuth()
  File "/home/MYNAME/dev/BAZ/BAZ_env/lib/python3.5/site-packages/pydrive2/auth.py", line 130, in _decorated
    self.Refresh()
  File "/home/MYNAME/dev/BAZ/BAZ_env/lib/python3.5/site-packages/pydrive2/auth.py", line 544, in Refresh
    self.credentials.refresh(self.http)
  File "/home/MYNAME/dev/BAZ/BAZ_env/lib/python3.5/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/home/MYNAME/dev/BAZ/BAZ_env/lib/python3.5/site-packages/oauth2client/client.py", line 763, in _refresh
    self.store.release_lock()
  File "/home/MYNAME/dev/BAZ/BAZ_env/lib/python3.5/site-packages/oauth2client/client.py", line 368, in release_lock
    self._lock.release()
RuntimeError: release unlocked lock
```

**Comment by shcheklein** [comment]
@mozboz hmm, interesting. Could you share your code please (you can remove or hide sensitive stuff)?

In general it is thread safe, and should work fine. Check this client code - 

https://github.com/iterative/dvc/blob/master/dvc/remote/gdrive.py#L395

this function is called from multiple threads.

But it might be we are missing something here and there is some bug, so please share the code, we will try to take a look.

**Comment by shcheklein** [comment]
Closing as stale.
