### ISSUE TITLE
"Error 403 : Daily Limit for Unauthenticated Use Exceeded" when downloading public files

### ISSUE THREAD

**Issue by laszloturanyi** [iterative/PyDrive2#60]
Hi,

I try to downlaod [this zip](https://drive.google.com/file/d/1WvlAIvuochQn_L_f9p3OdFdTiSLlnnhv/view?usp=sharing) containing 70000 images with the following script. Before, I Enabled Google API and placed client_secrets.json in the folder where the script is.

I am using version 1.6.2 in a conda environment

```python
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive

gauth = GoogleAuth()
gauth.LocalWebserverAuth()
drive = GoogleDrive(gauth)

file_id ='1WvlAIvuochQn_L_f9p3OdFdTiSLlnnhv'

file = drive.CreateFile({'id': file_id})
file.GetContentFile('images.zip')
```
**However, running the script it raises the following error after a successful authorization**

```
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=971122666526-nf9j40v6nsh3dck4ki9535h1uv18lsf0.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code

Authentication successful.
Traceback (most recent call last):
  File "/home/tlaci/anaconda3/envs/pydrive/lib/python3.8/site-packages/pydrive2/files.py", line 358, in GetContentFile
    download(fd, files.get_media(fileId=file_id))
  File "/home/tlaci/anaconda3/envs/pydrive/lib/python3.8/site-packages/pydrive2/files.py", line 348, in download
    status, done = downloader.next_chunk()
  File "/home/tlaci/anaconda3/envs/pydrive/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/tlaci/anaconda3/envs/pydrive/lib/python3.8/site-packages/googleapiclient/http.py", line 749, in next_chunk
    raise HttpError(resp, content, uri=self._uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files/1WvlAIvuochQn_L_f9p3OdFdTiSLlnnhv?alt=media returned "The download quota for this file has been exceeded">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_pydrive2.py", line 11, in <module>
    file.GetContentFile('images.zip') # downloads 'My Awesome File.txt' as 'my-awesome-file.txt'
  File "/home/tlaci/anaconda3/envs/pydrive/lib/python3.8/site-packages/pydrive2/auth.py", line 84, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/home/tlaci/anaconda3/envs/pydrive/lib/python3.8/site-packages/pydrive2/files.py", line 386, in GetContentFile
    raise exc
pydrive2.files.ApiRequestError: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files/1WvlAIvuochQn_L_f9p3OdFdTiSLlnnhv?alt=media returned "The download quota for this file has been exceeded">
```
** Also, detailed .json description above error says authenticated use exceeded. How could it be unauthenticated if I just finished authentication with success?**

```json
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

I would be glad if someone could help me with this issue.

Regards,
Laci

**Comment by shcheklein** [comment]
I think this is happens because this file was published publicly:

```
Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.
```

there is nothing you can do I guess, just wait.

**Comment by laszloturanyi** [comment]
@shcheklein 

This message suggested me the problem is on my side:
Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.

What does signing up means in this context?

**Comment by shcheklein** [comment]
@laszloturanyi my take on this that it means that message is misleading/bad.
