### ISSUE TITLE
google auth error

### ISSUE THREAD

**Issue by hagemouse** [iterative/PyDrive2#92]
After running for some time, following error ocrred:

```
[2021-02-28 17:11:23,950]  INFO {oauth2client.client:777} Refreshing access_token
[2021-02-28 17:11:24,204]  INFO {oauth2client.client:806} Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
[2021-02-28 17:11:24,209]  INFO {oauth2client.client:777} Refreshing access_token
Access token refresh failed: invalid_grant: Token has been expired or revoked.
[2021-02-28 17:11:24,285]  INFO {oauth2client.client:806} Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
Traceback (most recent call last):
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/pydrive2/auth.py", line 544, in Refresh
    self.credentials.refresh(self.http)
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/oauth2client/client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Token has been expired or revoked.
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/home/km/googlefileman/googlefile.py", line 152, in main
    gauth.Refresh()
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/pydrive2/auth.py", line 546, in Refresh
    raise RefreshError("Access token refresh failed: %s" % error)
pydrive2.auth.RefreshError: Access token refresh failed: invalid_grant: Token has been expired or revoked.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/pydrive2/auth.py", line 544, in Refresh
    self.credentials.refresh(self.http)
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/oauth2client/client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Token has been expired or revoked.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/km/googlefileman/googlefile.py", line 203, in <module>
    main()
  File "/home/km/googlefileman/googlefile.py", line 153, in main
    gauth.LocalWebserverAuth()
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/pydrive2/auth.py", line 130, in _decorated
    self.Refresh()
  File "/home/km/.local/share/virtualenvs/kl/lib/python3.8/site-packages/pydrive2/auth.py", line 546, in Refresh
    raise RefreshError("Access token refresh failed: %s" % error)
pydrive2.auth.RefreshError: Access token refresh failed: invalid_grant: Token has been expired or revoked.
```

```python
code:
    gauth = GoogleAuth()
    gauth.LoadCredentialsFile("mycreds.txt")
    if gauth.credentials is None:
        gauth.LocalWebserverAuth()
    elif gauth.access_token_expired:
        try:
            gauth.Refresh()
        except Exception as e:
            gauth.LocalWebserverAuth()
    else:
        gauth.Authorize()
```

And I have to delete mycreds.txt to make it work again.

**Comment by shcheklein** [comment]
@hagemouse what version of the PyDrive2 do you use? Do you use the settings file? You should specify path to the credentials in it https://iterative.github.io/PyDrive2/docs/build/html/oauth.html#authentication-in-two-lines.

You don't usually need to load files manually, or run refresh on your own.

**Comment by hagemouse** [comment]
I tried that, putting "client_secrets.json"  in my working directory. But it doesn't work and I have to do authentication every time.

**Comment by shcheklein** [comment]
I think you need to create the `settings.yaml` file and set those vars:

```
save_credentials: {{bool}}
save_credentials_backend: {{str}}
save_credentials_file: {{str}}

get_refresh_token: {{bool}}
```

as described here https://iterative.github.io/PyDrive2/docs/build/html/oauth.html#automatic-and-custom-authentication-with-settings-yaml


could you give a try please?

**Comment by hagemouse** [comment]
settings.yaml :

client_config_backend: settings
client_config:
  client_id: 357702-8qcmu5a1n64mn.apps.googleusercontent.com
  client_secret: aVyu5KZ8KYQ

save_credentials: True
save_credentials_backend: file
save_credentials_file: client_secrets.json
get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
  - https://www.googleapis.com/auth/drive.metadata

Run:
    gauth = GoogleAuth()
    gauth.LoadCredentialsFile()

Following Error:

Traceback (most recent call last):

    gauth.LoadCredentialsFile()
  File "/home/karlmarx/.local/share/virtualenvs/karlmarx-u6_2a8iz/lib/python3.8/site-packages/pydrive2/auth.py", line 350, in LoadCredentialsFile
    self.credentials = storage.get()
  File "/home/karlmarx/.local/share/virtualenvs/karlmarx-u6_2a8iz/lib/python3.8/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/home/karlmarx/.local/share/virtualenvs/karlmarx-u6_2a8iz/lib/python3.8/site-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/home/karlmarx/.local/share/virtualenvs/karlmarx-u6_2a8iz/lib/python3.8/site-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

**Comment by shcheklein** [comment]
I think you don't need `gauth.LoadCredentialsFile()`, why do you run it?

**Comment by hagemouse** [comment]
You are very right. Thank you very much.

I just followed the example.  Sorry for not learning pydrive2 well enough.

**Comment by shcheklein** [comment]
No worries! Happy to help @hagemouse .
